name: Build Traxxion09 tunnel pro APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools-version: 33.0.0
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: traxxion09-tunnel-pro-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Traxxion09 tunnel pro v1.0.${{ github.run_number }}
        body: |
          🚀 **Traxxion09 tunnel pro** - VPN App for Zimbabwe
          
          **Features:**
          - ✅ 10-second splash screen with "Created by LilGagaTraxx09"
          - ✅ 8 Zimbabwean servers (Econet & NetOne)
          - ✅ Offline mode functionality
          - ✅ Import/Export configuration
          - ✅ Contact: 263780078177, 263716857999
          
          **Developer:** Vincent Ganiza LilGagaTraxx09
          
          **Installation:**
          1. Download the APK below
          2. Enable "Unknown Sources" on Android
          3. Install and enjoy!
        draft: false
        prerelease: false